apiVersion: v2
name: network-scanner
description: A Helm chart for deploying network-scanner
type: application
version: 0.2.0
appVersion: '0.1.0'
dependencies:
  - name: redis
    repository: https://groundhog2k.github.io/helm-charts/
    version: 2.3.1
  - name: couchdb
    repository: https://apache.github.io/couchdb-helm
    version: 4.6.3
maintainers:
  - name: bryopsida